from setuptools import setup, find_packages

print('Found packages:', find_packages())
setup(
    description='HRM as a package',
    name='HRM',
    packages=find_packages(),
    install_requires=[
        'gdown',
        'numpy',
        'opencv-python',
        'pyrender',
        'pytorch-lightning',
        'scikit-image',
        'smplx==0.1.28',
        'yacs',
        'detectron2 @ git+https://gitclone.com/github.com/facebookresearch/detectron2',
        'chumpy @ git+https://gitclone.com/github.com/mattloper/chumpy',
        'mmcv==1.3.9',
        'timm',
        'einops',
        'xtcocotools',
        'pandas',
        'open3d',
        'decord',
        'loguru',
        'webdataset',
        'simple-knn @ git+https://github.com/camenduru/simple-knn/',
        'diff-gaussian-rasterization @ git+https://github.com/ashawkey/diff-gaussian-rasterization/',
        'diffusers',
        'plyfile',
        'jaxtyping',
        'lpips',
        'pytorch-msssim',
        'megfile',
        'typeguard',
        'accelerate',
        'wandb',
        'imageio-ffmpeg',
        'transformers @ git+https://github.com/huggingface/transformers',
        'kornia',
    ],
    extras_require={
        'all': [
            'hydra-core',
            'hydra-submitit-launcher',
            'hydra-colorlog',
            'pyrootutils',
            'rich',
        ],
    },
)
